<?php
namespace frontend\controllers;



use backend\models\GoodsCategory;
use frontend\models\LoginForm;
use frontend\models\Member;
use yii\web\Controller;
use yii\web\Response;
use frontend\models\Address;

//API接口开发
class ApiController extends Controller{

    //关闭csrf验证
    public $enableCsrfValidation = false;

    //设置响应数据格式
    public function init()
    {
        \Yii::$app->response->format=Response::FORMAT_JSON;
        parent::init(); // TODO: Change the autogenerated stub
    }
    //会员注册接口
    public function actionRegist(){
        $result=[
            'error'=>null,
            'msg'=>'',
            'data'=>[],
        ];

        $model=new \frontend\models\LoginForm();
        //设置场景
        $model->scenario=LoginForm::SCENARIO_Regist;
        $request=\Yii::$app->request;
        if($request->isPost){
            $model->load($request->post(),'');
            if($model->validate()){
                //验证用户名唯一性
                $member=Member::findOne(['username'=>$model->username]);
               if($member){
                   $result['error']=1;
                   $result['msg']='用户名已存在';
               }else{
                   $user=new Member();
                   $user->username=$model->username;
                   $user->password_hash=\Yii::$app->security->generatePasswordHash($model->password);
                   $user->email=$model->email;
                   $user->tel=$model->tel;
                   $user->save();
                   $result['msg']='注册成功';
               }

            }else{
                //提示用户完善信息
                $result['error']=1;
                $result['msg']='请完善注册信息';
            }
        }
        return $result;



    }

    //会员登录接口
    public function actionLogin(){
        $result=[
            'error'=>null,
            'msg'=>'',
            'data'=>[],
        ];
        //得到用户名个密码
        $username=\Yii::$app->request->post('username');
        $password=\Yii::$app->request->post('password');
        //根据用户名查询
        $member=Member::findOne(['username'=>$username]);
        //如果用户存在
        if($member){
            if(\Yii::$app->security->validatePassword($password,$member->password_hash)){
                \Yii::$app->user->login($member);
                $result['data']=[
                    'id'=>$member->id,
                    'username'=>$member->username,
                ];
                $result['msg']='登录成功';

            }else{
                $result['error']=1;
                $result['msg']='密码错误';
                }
            }else{
            $result['error']=1;
            $result['msg']='用户名错误';
        }

        return $result;
    }
    //修改密码接口
    public function actionPwd(){
        //返回结果
        $result=[
            'error'=>null,
            'msg'=>'',
            'data'=>[],
        ];
        //得到表单数据
        $oldpassword=\Yii::$app->request->post('oldpassword');
        $password=\Yii::$app->request->post('password');
        $repassword=\Yii::$app->request->post('repassword');
        $id=\Yii::$app->user->id;
        $member=Member::findOne(['id'=>$id]);

                //如果验证成功,保存数据
                if(\Yii::$app->security->validatePassword($oldpassword,$member->password_hash)){
                    if($password==$repassword){
                        Member::updateAll([
                            'password_hash'=>\Yii::$app->security->generatePasswordHash($password)
                        ],
                            [
                                'id'=>$id
                            ]);

                        $result['msg']='密码修改成功';
                    }else{
                        $result['error']=1;
                        $result['msg']='两次密码不一致';
                    }

                }else{
                    $result['error']=1;
                    $result['msg']='旧密码不正确';
                }

        return $result;
    }

    //获取当前登录信息接口
    public function actionInfo(){
        //返回结果
        $result=[
            'error'=>null,
            'msg'=>'',
            'data'=>[],
        ];
        //得到登录id
        $id=\Yii::$app->user->id;
        if($id){
            $member=Member::findOne(['id'=>$id]);
            $result['data']=[
                'id'=>$member->id,
                'username'=>$member->username,
                'email'=>$member->email,
                'tel'=>$member->tel,
                'last_login_time'=>$member->last_login_time,
                'last_login_ip'=>$member->last_login_time,
            ];
        }
        return $result;
    }

    //收货接口
        //添加地址接口
    public function actionAddressAdd(){
        //返回结果
        $result=[
            'error'=>null,
            'msg'=>'',
            'data'=>[],
        ];
        $requset=\Yii::$app->request;
        $model=new Address();
        if($requset->isPost){
            $model->load($requset->post(),'');

            if($model->validate()){
                $model->member_id=\Yii::$app->user->identity->id;
                $model->save();
                $result['msg']='添加地址成功';
                $result['data']=$model;
            }else{
                $result['error']=1;
                $result['msg']='请完善地址信息';
            }
        }
        return $result;
    }

    //地址修改接口
    public function actionAddressEdit(){
        //返回结果
        $result=[
            'error'=>null,
            'msg'=>'',
            'data'=>[],
        ];
               $requset=\Yii::$app->request;
        $model=new Address();
        $id=\Yii::$app->request->get('id');
        $model=Address::findOne(['id'=>$id]);
        if($requset->isPost){
            $model->load($requset->post(),'');

            if($model->validate()){
                $model->member_id=\Yii::$app->user->identity->id;
                $model->save();
                $result['msg']='修改地址成功';
                $result['data']=$model;
            }else{
                $result['error']=1;
                $result['msg']='请完善地址信息';
            }
        }
        return $result;

    }

    //地址删除接口
    public function actionAddressDel(){
        //返回结果
        $result=[
            'error'=>null,
            'msg'=>'',
            'data'=>[],
        ];
        $requset=\Yii::$app->request;
        $id=$requset->post('id');
        $del=Address::findOne(['id'=>$id]);
        if($del){
            $del->delete();
            $result['msg']='删除成功';
        }else{
            $result['error']=1;
            $result['msg']='删除失败';
        }
        return $result;
    }

    //地址列表接口
    public function actionAddressList(){
        //返回结果
        $result=[
            'error'=>null,
            'msg'=>'',
            'data'=>[],
        ];
        $lists=Address::find()->where(['member_id'=>\Yii::$app->user->identity->id])->all();
        $result['data']=$lists;
        return $result;
    }

    //商品分类接口
        //获取所有商品分类
    public function actionGoodsCategoryList(){
        //返回结果
        $result=[
            'error'=>null,
            'msg'=>'',
            'data'=>[],
        ];
        $lists=GoodsCategory::find()->all();
        $result['data']=$lists;
        return $result;
    }

    //获取某分类的所有子分类
}