<?php
namespace backend\filters;

use yii\base\ActionFilter;
use yii\web\HttpException;

class RbacFilter extends  ActionFilter{

    public function beforeAction($action)
    {   if(!\Yii::$app->user->can($action->uniqueId)){
//       echo '<pre>' ;var_dump(\Yii::$app->user);die;
            if(\Yii::$app->user->isGuest){
                return $action->controller->redirect(\Yii::$app->user->loginUrl)->send();
            }else{
//                 if(\Yii::$app->user->loginUrl=='user/login'){
//
//                 }

                throw new HttpException(403,'你没有权限');
                return false;
            }

    }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub

    }
}